# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(413, 523)
        MainWindow.setStyleSheet("background-color: rgb(44, 44, 44);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.push_plus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_plus.sizePolicy().hasHeightForWidth())
        self.push_plus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.push_plus.setFont(font)
        self.push_plus.setStyleSheet("QPushButton{\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(223, 223, 0);\n"
"    border-radius:35px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(94, 94, 94);\n"
"    \n"
"    background-color: rgb(177, 177, 0);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_plus.setObjectName("push_plus")
        self.gridLayout.addWidget(self.push_plus, 1, 3, 1, 1)
        self.push_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_1.sizePolicy().hasHeightForWidth())
        self.push_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.push_1.setFont(font)
        self.push_1.setStyleSheet("QPushButton{\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(181, 181, 181);\n"
"    border-radius:35px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(94, 94, 94);\n"
"    background-color: rgb(139, 139, 139);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_1.setObjectName("push_1")
        self.gridLayout.addWidget(self.push_1, 2, 0, 1, 1)
        self.push_del = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_del.sizePolicy().hasHeightForWidth())
        self.push_del.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.push_del.setFont(font)
        self.push_del.setStyleSheet("QPushButton{\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(181, 181, 181);\n"
"    border-radius:35px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(94, 94, 94);\n"
"    background-color: rgb(139, 139, 139);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_del.setObjectName("push_del")
        self.gridLayout.addWidget(self.push_del, 1, 2, 1, 1)
        self.push_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_2.sizePolicy().hasHeightForWidth())
        self.push_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.push_2.setFont(font)
        self.push_2.setStyleSheet("QPushButton{\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(181, 181, 181);\n"
"    border-radius:35px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(94, 94, 94);\n"
"    background-color: rgb(139, 139, 139);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_2.setObjectName("push_2")
        self.gridLayout.addWidget(self.push_2, 2, 1, 1, 1)
        self.push_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_7.sizePolicy().hasHeightForWidth())
        self.push_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.push_7.setFont(font)
        self.push_7.setStyleSheet("QPushButton{\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(181, 181, 181);\n"
"    border-radius:35px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(94, 94, 94);\n"
"    background-color: rgb(139, 139, 139);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_7.setObjectName("push_7")
        self.gridLayout.addWidget(self.push_7, 4, 0, 1, 1)
        self.push_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_5.sizePolicy().hasHeightForWidth())
        self.push_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.push_5.setFont(font)
        self.push_5.setStyleSheet("QPushButton{\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(181, 181, 181);\n"
"    border-radius:35px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(94, 94, 94);\n"
"    background-color: rgb(139, 139, 139);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_5.setObjectName("push_5")
        self.gridLayout.addWidget(self.push_5, 3, 1, 1, 1)
        self.push_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_4.sizePolicy().hasHeightForWidth())
        self.push_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.push_4.setFont(font)
        self.push_4.setStyleSheet("QPushButton{\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(181, 181, 181);\n"
"    border-radius:35px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(94, 94, 94);\n"
"    background-color: rgb(139, 139, 139);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_4.setObjectName("push_4")
        self.gridLayout.addWidget(self.push_4, 3, 0, 1, 1)
        self.push_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_6.sizePolicy().hasHeightForWidth())
        self.push_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.push_6.setFont(font)
        self.push_6.setStyleSheet("QPushButton{\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(181, 181, 181);\n"
"    border-radius:35px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(94, 94, 94);\n"
"    background-color: rgb(139, 139, 139);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_6.setObjectName("push_6")
        self.gridLayout.addWidget(self.push_6, 3, 2, 1, 1)
        self.push_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_8.sizePolicy().hasHeightForWidth())
        self.push_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.push_8.setFont(font)
        self.push_8.setStyleSheet("QPushButton{\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(181, 181, 181);\n"
"    border-radius:35px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(94, 94, 94);\n"
"    background-color: rgb(139, 139, 139);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_8.setObjectName("push_8")
        self.gridLayout.addWidget(self.push_8, 4, 1, 1, 1)
        self.push_multiply = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_multiply.sizePolicy().hasHeightForWidth())
        self.push_multiply.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.push_multiply.setFont(font)
        self.push_multiply.setStyleSheet("QPushButton{\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(223, 223, 0);\n"
"    border-radius:35px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(94, 94, 94);\n"
"    \n"
"    background-color: rgb(177, 177, 0);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_multiply.setObjectName("push_multiply")
        self.gridLayout.addWidget(self.push_multiply, 3, 3, 1, 1)
        self.push_minus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_minus.sizePolicy().hasHeightForWidth())
        self.push_minus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.push_minus.setFont(font)
        self.push_minus.setStyleSheet("QPushButton{\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(223, 223, 0);\n"
"    border-radius:35px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(94, 94, 94);\n"
"    \n"
"    background-color: rgb(177, 177, 0);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_minus.setObjectName("push_minus")
        self.gridLayout.addWidget(self.push_minus, 2, 3, 1, 1)
        self.push_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_3.sizePolicy().hasHeightForWidth())
        self.push_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.push_3.setFont(font)
        self.push_3.setStyleSheet("QPushButton{\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(181, 181, 181);\n"
"    border-radius:35px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(94, 94, 94);\n"
"    background-color: rgb(139, 139, 139);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_3.setObjectName("push_3")
        self.gridLayout.addWidget(self.push_3, 2, 2, 1, 1)
        self.push_share = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_share.sizePolicy().hasHeightForWidth())
        self.push_share.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.push_share.setFont(font)
        self.push_share.setStyleSheet("QPushButton{\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(223, 223, 0);\n"
"    border-radius:35px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(94, 94, 94);\n"
"    \n"
"    background-color: rgb(177, 177, 0);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_share.setObjectName("push_share")
        self.gridLayout.addWidget(self.push_share, 4, 3, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushButton_19.sizePolicy().hasHeightForWidth())
        self.pushButton_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet("QPushButton{\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(181, 181, 181);\n"
"    border-radius:35px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(94, 94, 94);\n"
"    background-color: rgb(139, 139, 139);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 5, 2, 1, 1)
        self.push_9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_9.sizePolicy().hasHeightForWidth())
        self.push_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.push_9.setFont(font)
        self.push_9.setStyleSheet("QPushButton{\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(181, 181, 181);\n"
"    border-radius:35px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(94, 94, 94);\n"
"    background-color: rgb(139, 139, 139);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_9.setObjectName("push_9")
        self.gridLayout.addWidget(self.push_9, 4, 2, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy)
        self.pushButton_20.setStyleSheet("QPushButton{\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(223, 223, 0);\n"
"    border-radius:35px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(94, 94, 94);\n"
"    \n"
"    background-color: rgb(177, 177, 0);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_20, 5, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(13)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("font: 75 24pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255)")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.push_clear = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_clear.sizePolicy().hasHeightForWidth())
        self.push_clear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.push_clear.setFont(font)
        self.push_clear.setStyleSheet("QPushButton{\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(181, 181, 181);\n"
"    border-radius:35px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(94, 94, 94);\n"
"    background-color: rgb(139, 139, 139);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_clear.setObjectName("push_clear")
        self.gridLayout.addWidget(self.push_clear, 1, 0, 1, 2)
        self.push_0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_0.sizePolicy().hasHeightForWidth())
        self.push_0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.push_0.setFont(font)
        self.push_0.setStyleSheet("QPushButton{\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(181, 181, 181);\n"
"    border-radius:35px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(94, 94, 94);\n"
"    background-color: rgb(139, 139, 139);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_0.setObjectName("push_0")
        self.gridLayout.addWidget(self.push_0, 5, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.push_plus.setText(_translate("MainWindow", "+"))
        self.push_1.setText(_translate("MainWindow", "1"))
        self.push_del.setText(_translate("MainWindow", "Del"))
        self.push_2.setText(_translate("MainWindow", "2"))
        self.push_7.setText(_translate("MainWindow", "7"))
        self.push_5.setText(_translate("MainWindow", "5"))
        self.push_4.setText(_translate("MainWindow", "4"))
        self.push_6.setText(_translate("MainWindow", "6"))
        self.push_8.setText(_translate("MainWindow", "8"))
        self.push_multiply.setText(_translate("MainWindow", "X"))
        self.push_minus.setText(_translate("MainWindow", "-"))
        self.push_3.setText(_translate("MainWindow", "3"))
        self.push_share.setText(_translate("MainWindow", "/"))
        self.pushButton_19.setText(_translate("MainWindow", "."))
        self.push_9.setText(_translate("MainWindow", "9"))
        self.pushButton_20.setText(_translate("MainWindow", "="))
        self.push_clear.setText(_translate("MainWindow", "Clear"))
        self.push_0.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
