# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(428, 518)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #22222e")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 431, 270))
        self.widget.setStyleSheet("background-color: #22222e")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(120, 10, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(120, 80, 181, 131))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("iconConv.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.input_cur = QtWidgets.QLineEdit(self.centralwidget)
        self.input_cur.setGeometry(QtCore.QRect(20, 360, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(20)
        self.input_cur.setFont(font)
        self.input_cur.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #00aaff;\n"
"border-radius: 20;\n"
"color: white;")
        self.input_cur.setText("")
        self.input_cur.setAlignment(QtCore.Qt.AlignCenter)
        self.input_cur.setObjectName("input_cur")
        self.input_sum = QtWidgets.QLineEdit(self.centralwidget)
        self.input_sum.setGeometry(QtCore.QRect(20, 280, 191, 60))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(20)
        self.input_sum.setFont(font)
        self.input_sum.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #00aaff;\n"
"border-radius: 20;\n"
"color: white;")
        self.input_sum.setText("")
        self.input_sum.setAlignment(QtCore.Qt.AlignCenter)
        self.input_sum.setObjectName("input_sum")
        self.output_cur = QtWidgets.QLineEdit(self.centralwidget)
        self.output_cur.setGeometry(QtCore.QRect(220, 360, 191, 60))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(20)
        self.output_cur.setFont(font)
        self.output_cur.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #00aaff;\n"
"border-radius: 20;\n"
"color: white;")
        self.output_cur.setText("")
        self.output_cur.setAlignment(QtCore.Qt.AlignCenter)
        self.output_cur.setObjectName("output_cur")
        self.output_sum = QtWidgets.QLineEdit(self.centralwidget)
        self.output_sum.setGeometry(QtCore.QRect(19, 440, 391, 60))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(20)
        self.output_sum.setFont(font)
        self.output_sum.setTabletTracking(False)
        self.output_sum.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #00aaff;\n"
"border-radius: 20;\n"
"color: white;")
        self.output_sum.setText("")
        self.output_sum.setAlignment(QtCore.Qt.AlignCenter)
        self.output_sum.setReadOnly(True)
        self.output_sum.setObjectName("output_sum")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 280, 191, 60))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"background-color: #fb5b5d;\n"
"border-radius: 20;\n"
"color: white;\n"
"} \n"
"QPushButton: pressed {\n"
"background-color: #fa4244;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Конвертер Валют"))
        self.pushButton.setText(_translate("MainWindow", "Конвертация"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
